INCLUDE_DIR = include/
COMPILE_ARGS = -std=c++17 -Wall -Wextra -ffunction-sections -fdata-sections -Og -g
SRC_FILES = src/alarm.cpp exercise02.cpp

all:
	g++ $(COMPILE_ARGS) -I$(INCLUDE_DIR) -o exercise02 $(SRC_FILES)


clean:
	rm exercise02